### ISSUE TITLE
Database ID and Name product overwrite when importing with CSV

### ISSUE THREAD

**Issue by jointsystems** [cardgate/prestashop16#10]
Briggs and Stratton's price list has over 100k items that are in constant flux.  When attempting to import products with similar names differing by one number or letter the database overwrites the existing product.
For instance  one model number is 19J137-0008-F1 whereas there is a sister product with a different sized crankshaft 19J137-0007-F1,  When you import either one using the model number for the name it overwrites the other and you end up with the product name of the one just imported but the description and images of the other often both products disappear and cannot be found with a product search after updating the search after the import ,   We normally use the model number as the ID but when that did not work we tried using the original vendor number and the UPC number as the ID and tried the same changes with the name to no avail?

**Comment by cardgate** [comment]
Our CardGate module does not affect the importing of products in any way. My suggestion is to do a search on the words: prestashop 1.6 import products

**Comment by jointsystems** [comment]
I did a search for 1.6.23 issues and failed to notice that this was under cardgate rather than PrestaShop directly.
